### ISSUE TITLE
I cannot open configuration UI of host what created by API

### ISSUE THREAD

**Issue by meishao** [tenable/Tenable.io-SDK-for-Python#6]
I tried the following sample code to create a new scan for specified host.
```python
        scan = client.scan_helper.create(
            name="example.com", 
            text_targets="example.com",
            template="basic"
        )
```
And I access the https://cloud.tenable.com, I found that cannot open UI of basic configuration detail.
I checked the console output of browser chrome, the following error was occurred.
```
Uncaught TypeError: Cannot read property 'freq' of null
    at scans.editor (shared.js?v=13:3)
    at a.value (shared.js?v=13:4)
    at a.value (shared.js?v=13:4)
    at a.value (shared.js?v=13:4)
    at a.value (scans.js?v=13:15)
    at scans.js?v=13:15
    at a.value (scans.js?v=13:15)
    at scans.js?v=13:15
    at a.value (shared.js?v=13:4)
    at scans.js?v=13:15
```
Could you help me to fix this problem?

**Comment by meishao** [comment]
@alanfung @kagutagu Could you please check this issue?

**Comment by morganney** [comment]
I believe this is due to [defaulting enabled to `True` in `ScansSettings`](https://github.com/tenable/Tenable.io-SDK-for-Python/blob/master/tenable_io/api/models.py#L892).  The example does not define a schedule for the scan, but since the schedule has been enabled the UI is throwing an error due to their being no schedule information (`rrules`, `starttime`, or `timezone`).

The [API documentation for scans](https://cloud.tenable.com/api#/resources/scans) states that `enabled` turns on the scans schedule, so perhaps it should default to `False` and only set to`True` when passing schedule arguments to `scan_helper.create`?
